name: flux_i18n
version: 0.2.1
description: Localization for flux library.
dependencies:
  browser: any
  flux:
    git: https://github.com/jakuub/flux.git
  tiles: any
  vacuum_persistent: '>=2.0.0'
dev_dependencies:
  mock: any
  unittest: any
